### ISSUE TITLE
Not working with Docpad 6.80.3

### ISSUE THREAD

**Issue by johnwu** [docpad/docpad-plugin-consolidate#6]
Was working with docpad 6.79.4, but after updating to 6.80.3 seeing the following error:

```
[33mwarning:[39m Failed to load the plugin: docpad-plugin-consolidate at /Volumes/Data/Users/username/Documents/projects/website/node_modules/docpad-plugin-consolidate
The error follows:

TypeError: Class constructor BasePlugin cannot be invoked without 'new'
    at new ConsolidatePlugin (/Volumes/Data/Users/username/Documents/projects/website/node_modules/docpad-plugin-consolidate/out/lib/consolidate.plugin.js:23:49)
    at PluginLoader.create (/Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:260:26)
    at /Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/docpad.js:3600:29
    at PluginLoader.load (/Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:240:7)
    at /Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/docpad.js:3595:27
    at PluginLoader.unsupported (/Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:146:7)
    at /Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/docpad.js:3573:25
    at success (/Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:71:16)
    at safefs.readFile (/Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:110:18)
    at /Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by RobLoach** [comment]
Thanks! Likely could do with an update.

**Comment by johnwu** [comment]
How about transferring it Docpad to maintain?
https://docpad.org/docs/plugin-write#maintenance

**Comment by RobLoach** [comment]
Great idea! Done... https://github.com/docpad/docpad-plugin-consolidate

**Comment by balupton** [comment]
Package just needs https://github.com/bevry/boundation run on it.

For the meantime, you can get compatibility by running the following:

```
env EDITIONS_SYNTAX_BLACKLIST=esnext docpad run
```

**Comment by balupton** [comment]
@RobLoach can you run:

- `npm owner add balupton docpad-plugin-consolidate`
- `npm owner add bevryme docpad-plugin-consolidate`

**Comment by RobLoach** [comment]
Thanks :+1:

**Comment by balupton** [comment]
I've got it going locally, but too tired to push up today. Will do it over the next few days.

**Comment by balupton** [comment]
v2.3.0 now out which resolves this issue
